package enumConstant;

public enum  ServerRequest {

    SIGNUP_REQUEST("0"),
    STUDENT_LOGIN_REQUEST("1"),
    TEACHER_LOGIN_REQUEST("2"),
    SUBJECT_ADD_REQUEST("3"),
    EXAM_ADD_REQUEST("4"),
    SUBJECT_LIST_FETCH_REQUEST("5"),
    EXAM_LIST_FETCH_REQUEST("6"),
    SECTION_ADD_REQUEST("7"),
    SECTION_FETCH_REQUEST("8"),
    QUESTION_ADD_REQUEST("9"),
    QUESTION_FETCH_REQUEST("10"),
    QUIZ_ADD_REQUEST("11"),
    QUIZ_FETCH_REQUEST("12"),
    QUESTION_LIST_FETCH_STUDENT_REQUEST("13"),
    RATING_ADD_REQUEST("14"),
    RATING_FETCH_REQUEST("15"),
    SCORE_FETCH_REQUEST("16"),
    SCORE_ADD_REQUEST("17"),
    RANK_FETCH_REQUEST("18"),
    QUIZ_BY_STUDENT_REQUEST("19"),
    COMMENT_ADD_REQUEST("20"),
    COMMENT_FETCH_REQUEST("21"),
    QUIZ_LIST_FETCH_TEACHER_REQUEST("22")
    ;

    ServerRequest(String s){
        s.toString();
    }
}
